### PR TITLE
parquet4seastar

### PR DESCRIPTION
**Pull request by michoecho**
Continued from https://github.com/psarna/seastar/pull/98.

### CODE REVIEW

**Comment by psarna** [comment]
Good to go, nice seastar integration with CMake.
As for cql_reader - it can indeed be moved to another directory, e.g. straight to `apps/parquet2cql`, but it shouldn't block this series - feel free to merge this pull request.

**Comment by psarna** [comment]
Let's merge to master - are you still working on the lately added commits, or is this whole pull request good to go?

**Comment by michoecho** [comment]
If you have no further comments, then I guess we can merge it.

**Comment by psarna** [comment]
Thx. I'll push the official announcement to seastar-dev and scylladb-dev either on Sunday or Monday.

**Pull request merged**
